
# User manual
user-manual /usr/share/doc/privoxy/user-manual


# CONFIGURATION AND LOG FILE LOCATIONS

confdir /etc/privoxy
logdir /var/log/privoxy

actionsfile match-all.action # Actions that are applied to all sites and maybe overruled later on.
actionsfile default.action   # Main actions file
actionsfile user.action      # User customizations

filterfile default.filter
filterfile user.filter      # User customizations

logfile logfile


#  ACCESS CONTROL AND SECURITY

listen-address  127.0.0.1:8118
listen-address  [::1]:8118
forward / localhost:8123

toggle  1
enable-remote-toggle  0
enable-remote-http-toggle  0
enable-edit-actions 0

enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 0


#  FORWARDING
forwarded-connect-retries  0


#  MISCELLANEOUS

accept-intercepted-requests 0
allow-cgi-request-crunching 0

split-large-forms 0

keep-alive-timeout 5
tolerate-pipelining 1

socket-timeout 300
max-client-connections 256

#  WINDOWS GUI OPTIONS

activity-animation   1
show-on-task-bar 1
